###GET 
GET http://localhost:3000/products

###GET BY ID
GET http://localhost:3000/products/4


###POST
POST http://localhost:3000
Content-Type: application/json

{
  "Title": "test product",
  "Description": "Test",
  "Amount": 5,
  "Price": 7
}


###PUT
PUT http://localhost:3000
Content-Type: application/json

{
  "Id": 6,
  "Title": "Product 1",
  "Description": "Test",
  "Amount": 5,
  "Price": 7
}

###DELETE
DELETE http://localhost:3000/5


###404CHECK
GET http://localhost:3000/api